
/**************************************************************** 
* WARNING: This file is automatically generated. DO NOT EDIT IT!
*
* COPYRIGHT (c) Freescale 2004-2012, All Rights Reserved
* COPYRIGHT (c) NXP SEMICONDUCTORS INC. 2020, All Rights Reserved
*
* FILE NAME: etpu_mc_sin_auto.h
* COMPILER: CODEWARRIOR
* ARCHITECTURE: eTPU
*
* File Version: 3.0
* This file was generated by: etpuc_mc_sin.c at Aug 24 2020 10:54:33
*
* This file provides an interface between eTPU code and CPU
* code. All references to the eTPU function should be made with
* information in this file. This allows only symbolic
* information to be referenced which allows the eTPU code to be
* optimized without effecting the CPU code.
*****************************************************************/
#ifndef _ETPU_MC_SIN_AUTO_H_
#define _ETPU_MC_SIN_AUTO_H_

#define FS_ETPU_MC_SIN_OFFSET_MCSINLUT 0xe4

#endif
