
/**************************************************************** 
* WARNING: This file is automatically generated. DO NOT EDIT IT!
*
* COPYRIGHT (c) Freescale 2004-2012, All Rights Reserved
* COPYRIGHT (c) NXP SEMICONDUCTORS INC. 2018-2020, All Rights Reserved
*
* FILE NAME: etpu_as_auto.h
* COMPILER: CODEWARRIOR
* ARCHITECTURE: eTPU
*
* File Version: 2.02
* This file was generated by: etpuc_as.c at Aug 24 2020 10:54:29
*
* This file provides an interface between eTPU code and CPU
* code. All references to the eTPU function should be made with
* information in this file. This allows only symbolic
* information to be referenced which allows the eTPU code to be
* optimized without effecting the CPU code.
*****************************************************************/
#ifndef _ETPU_AS_AUTO_H_
#define _ETPU_AS_AUTO_H_

/* Function Activity Debug */
#define FS_ETPU_AS_ACTIVITY_DEBUG 1

/* Function Configuration Information */
#define FS_ETPU_AS_FUNCTION_NUMBER 0
#define FS_ETPU_AS_TABLE_SELECT 1
#define FS_ETPU_AS_NUM_PARMS 0x60


/* Host Service Request Definitions */
#define FS_ETPU_AS_HSR_INIT_MODE_PERIODIC 7
#define FS_ETPU_AS_HSR_INIT_MODE_SYNC 5
#define FS_ETPU_AS_HSR_MEASURE_DC_OFFSETS 2

/* Function Mode Bit Definitions - phases */
#define FS_ETPU_AS_FM0_FRAME_PULSE_ON 1
#define FS_ETPU_AS_FM0_FRAME_PULSE_OFF 0
#define FS_ETPU_AS_FM1_CENTER_PULSE_ON (1 << 1)
#define FS_ETPU_AS_FM1_CENTER_PULSE_OFF (0 << 1)

/* Parameter Definitions */
#define FS_ETPU_AS_OFFSET_OPTIONS_POLARITY  0x0
#define FS_ETPU_AS_OFFSET_START_OFFSET  0x1
#define FS_ETPU_AS_OFFSET_OPTIONS_LINK  0x4
#define FS_ETPU_AS_OFFSET_PERIOD  0x5
#define FS_ETPU_AS_OFFSET_OPTIONS_IRQ  0x8
#define FS_ETPU_AS_OFFSET_PULSE_ADJUSTMENT_FRAME  0x9
#define FS_ETPU_AS_OFFSET_OPTIONS_CFIFO  0xc
#define FS_ETPU_AS_OFFSET_PULSE_ADJUSTMENT_CENTER 0xd
#define FS_ETPU_AS_OFFSET_SIGNAL_MASK_FRAME  0x10
#define FS_ETPU_AS_OFFSET_PULSE_WIDTH  0x11
#define FS_ETPU_AS_OFFSET_SIGNAL_MASK_CENTER  0x14
#define FS_ETPU_AS_OFFSET_FRAME_TIME  0x15
#define FS_ETPU_AS_OFFSET_SIGNAL_MASK_DC_OFFSET  0x18
#define FS_ETPU_AS_OFFSET_CENTER_TIME  0x19
#define FS_ETPU_AS_OFFSET_SECTOR  0x1c
#define FS_ETPU_AS_OFFSET_PWMM_SECTOR  0x1d
#define FS_ETPU_AS_OFFSET_PHASE_CURRENT_A_IDX  0x20
#define FS_ETPU_AS_OFFSET_PWMM_FRAME_TIME  0x21
#define FS_ETPU_AS_OFFSET_PHASE_CURRENT_B_IDX  0x24
#define FS_ETPU_AS_OFFSET_PWMM_PERIOD  0x25
#define FS_ETPU_AS_OFFSET_PHASE_CURRENT_C_IDX  0x28
#define FS_ETPU_AS_OFFSET_RESULT_QUEUE  0x29
#define FS_ETPU_AS_OFFSET_SIGNAL_COUNT  0x2c
#define FS_ETPU_AS_OFFSET_COMMAND_QUEUE  0x2d
#define FS_ETPU_AS_OFFSET_OPTIONS_PHASE_CURRENTS  0x30
#define FS_ETPU_AS_OFFSET_SIGNAL  0x31
#define FS_ETPU_AS_OFFSET_LINK_CHANS_FRAME_START  0x34
#define FS_ETPU_AS_OFFSET_LINK_CHANS_FRAME_END  0x38
#define FS_ETPU_AS_OFFSET_LINK_CHANS_CENTER_START 0x3c
#define FS_ETPU_AS_OFFSET_LINK_CHANS_CENTER_END  0x40
#define FS_ETPU_AS_OFFSET_CMD_IA_ADC0  0x44
#define FS_ETPU_AS_OFFSET_CMD_IA_ADC1  0x48
#define FS_ETPU_AS_OFFSET_CMD_IB_ADC0  0x4c
#define FS_ETPU_AS_OFFSET_CMD_IB_ADC1  0x50
#define FS_ETPU_AS_OFFSET_CMD_IC_ADC0  0x54
#define FS_ETPU_AS_OFFSET_CMD_IC_ADC1  0x58

/* Signal Structure Definitions */
#define FS_ETPU_AS_OFFSET_QUEUE_OFFSET  0x00
#define FS_ETPU_AS_OFFSET_GAIN  0x01
#define FS_ETPU_AS_OFFSET_DC_OFFSET  0x05
#define FS_ETPU_AS_OFFSET_FORGET_FACTOR 0x09
#define FS_ETPU_AS_OFFSET_VALUE  0x0D

/* Value Definitions */
#define FS_ETPU_AS_SIGNALS_MAX  8
#define FS_ETPU_AS_SIGNAL_STRUCT_SIZE  0x10

/* Polarity Options */
#define FS_ETPU_AS_POLARITY_PULSE_LOW  0
#define FS_ETPU_AS_POLARITY_PULSE_HIGH  1

/* Phase Currents Options */
#define FS_ETPU_AS_PHASE_CURRENTS_OFF  1
#define FS_ETPU_AS_PHASE_CURRENTS_ON  0

/* IRQ&DMA Options */
#define FS_ETPU_AS_IRQ_FRAME_PULSE_START  0x01
#define FS_ETPU_AS_IRQ_FRAME_PULSE_END  0x02
#define FS_ETPU_AS_IRQ_CENTER_PULSE_START 0x04
#define FS_ETPU_AS_IRQ_CENTER_PULSE_END  0x08

/* Link Options */
#define FS_ETPU_AS_LINK_FRAME_PULSE_START  0x01
#define FS_ETPU_AS_LINK_FRAME_PULSE_END  0x02
#define FS_ETPU_AS_LINK_CENTER_PULSE_START 0x04
#define FS_ETPU_AS_LINK_CENTER_PULSE_END  0x08

/* CFIFO Options */
#define FS_ETPU_AS_CFIFO_FRAME_PULSE_START  0x01
#define FS_ETPU_AS_CFIFO_FRAME_PULSE_END  0x02
#define FS_ETPU_AS_CFIFO_CENTER_PULSE_START 0x04
#define FS_ETPU_AS_CFIFO_CENTER_PULSE_END  0x08

#endif
